module.exports = {
  apps: [
    {
      name: "koratv-gateway",
      cwd: "/opt/koratv/koratv-web/streaming-gateway",
      script: "server.js",
      interpreter: "node",
      node_args: "--env-file=.env",
      exec_mode: "cluster",
      instances: "max",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      kill_timeout: 10000,
      listen_timeout: 60000,
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      env_production: {
        NODE_ENV: "production",
      },
    },
    {
      name: "koratv-match-sync",
      cwd: "/opt/koratv/koratv-web/secure-streaming",
      script: "scripts/match-sync-cron.js",
      interpreter: "node",
      node_args: "--env-file=.env",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      kill_timeout: 10000,
      restart_delay: 5000,
      env_production: {
        NODE_ENV: "production",
        MATCH_SOURCE_PROVIDER: "both",
        MATCH_SYNC_CRON: "*/10 * * * *",
        MATCH_SYNC_ON_START: "true",
        API_FOOTBALL_LIVE_DETAILS_REFRESH_MINUTES: "10",
        API_FOOTBALL_TODAY_REFRESH_MINUTES: "10",
        API_FOOTBALL_TOMORROW_REFRESH_HOURS: "12",
        API_FOOTBALL_STANDINGS_PER_SYNC: "1",
      },
    },
    {
      name: "koratv-daily-refresh",
      cwd: "/opt/koratv/koratv-web/secure-streaming",
      script: "scripts/daily-refresh-cron.js",
      interpreter: "node",
      node_args: "--env-file=.env",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      kill_timeout: 10000,
      restart_delay: 5000,
      env_production: {
        NODE_ENV: "production",
        MATCH_SOURCE_PROVIDER: "both",
        API_FOOTBALL_LIVE_DETAILS_REFRESH_MINUTES: "10",
        API_FOOTBALL_TODAY_REFRESH_MINUTES: "10",
        API_FOOTBALL_TOMORROW_REFRESH_HOURS: "12",
        API_FOOTBALL_STANDINGS_PER_SYNC: "1",
        DAILY_REFRESH_CRON: "59 23 * * *",
        DAILY_REFRESH_TIMEZONE: "Africa/Casablanca",
      },
    },
  ],
};
